import = ["~/.config/alacritty/nordfox.toml"]

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/bash"

[window]
padding.x = 16
padding.y = 14
decorations = "none"
opacity = 0.97
dimensions = { lines = 50, columns = 160 }

[keyboard]
bindings = [{ key = "F11", action = "ToggleFullscreen" }]

[font]
size = 9
